export const keys = {
  backquote: {
    code: "Backquote",
    id: 1,
    ru: {
      caseDown: `ё`,
      caseUp: `Ё`,
      caps: `Ё`,
      shiftCaps: `ё`,
    },
    en: {
      caseDown: `\``,
      caseUp: `~`,
      caps: `\``,
      shiftCaps: `~`,
    },
  },
  digit1: {
    code: "Digit1",
    id: 2,
    ru: {
      caseDown: `1`,
      caseUp: `!`,
      caps: `1`,
      shiftCaps: `!`,
    },
    en: {
      caseDown: `1`,
      caseUp: `!`,
      caps: `1`,
      shiftCaps: `!`,
    },
  },
  digit2: {
    code: "Digit2",
    id: 3,
    ru: {
      caseDown: `2`,
      caseUp: `"`,
      caps: `2`,
      shiftCaps: `"`,
    },
    en: {
      caseDown: `2`,
      caseUp: `@`,
      caps: `2`,
      shiftCaps: `@`,
    },
  },
  digit3: {
    code: "Digit3",
    id: 4,
    ru: {
      caseDown: `3`,
      caseUp: `№`,
      caps: `3`,
      shiftCaps: `№`,
    },
    en: {
      caseDown: `3`,
      caseUp: `#`,
      caps: `3`,
      shiftCaps: `#`,
    },
  },
  digit4: {
    code: "Digit4",
    id: 5,
    ru: {
      caseDown: `4`,
      caseUp: `;`,
      caps: `4`,
      shiftCaps: `;`,
    },
    en: {
      caseDown: `4`,
      caseUp: `$`,
      caps: `4`,
      shiftCaps: `$`,
    },
  },
  digit5: {
    code: "Digit5",
    id: 6,
    ru: {
      caseDown: `5`,
      caseUp: `%`,
      caps: `5`,
      shiftCaps: `%`,
    },
    en: {
      caseDown: `5`,
      caseUp: `%`,
      caps: `5`,
      shiftCaps: `%`,
    },
  },
  digit6: {
    code: "Digit6",
    id: 7,
    ru: {
      caseDown: `6`,
      caseUp: `:`,
      caps: `6`,
      shiftCaps: `:`,
    },
    en: {
      caseDown: `6`,
      caseUp: `^`,
      caps: `6`,
      shiftCaps: `^`,
    },
  },
  digit7: {
    code: "Digit7",
    id: 8,
    ru: {
      caseDown: `7`,
      caseUp: `?`,
      caps: `7`,
      shiftCaps: `?`,
    },
    en: {
      caseDown: `7`,
      caseUp: `&`,
      caps: `7`,
      shiftCaps: `&`,
    },
  },
  digit8: {
    code: "Digit8",
    id: 9,
    ru: {
      caseDown: `8`,
      caseUp: `*`,
      caps: `8`,
      shiftCaps: `*`,
    },
    en: {
      caseDown: `8`,
      caseUp: `*`,
      caps: `8`,
      shiftCaps: `*`,
    },
  },
  digit9: {
    code: "Digit9",
    id: 10,
    ru: {
      caseDown: `9`,
      caseUp: `(`,
      caps: `9`,
      shiftCaps: `(`,
    },
    en: {
      caseDown: `9`,
      caseUp: `(`,
      caps: `9`,
      shiftCaps: `(`,
    },
  },
  digit0: {
    code: "Digit0",
    id: 11,
    ru: {
      caseDown: `0`,
      caseUp: `)`,
      caps: `0`,
      shiftCaps: `)`,
    },
    en: {
      caseDown: `0`,
      caseUp: `)`,
      caps: `0`,
      shiftCaps: `)`,
    },
  },
  minus: {
    code: "Minus",
    id: 12,
    ru: {
      caseDown: `-`,
      caseUp: `_`,
      caps: `-`,
      shiftCaps: `_`,
    },
    en: {
      caseDown: `-`,
      caseUp: `_`,
      caps: `-`,
      shiftCaps: `_`,
    },
  },
  equal: {
    code: "Equal",
    id: 13,
    ru: {
      caseDown: `=`,
      caseUp: `+`,
      caps: `=`,
      shiftCaps: `+`,
    },
    en: {
      caseDown: `=`,
      caseUp: `+`,
      caps: `=`,
      shiftCaps: `+`,
    },
  },
  backspace: {
    code: "Backspace",
    key: "Backspace",
    id: 14,
    ru: {
      caseDown: `Backspace`,
      caseUp: `Backspace`,
      caps: `Backspace`,
      shiftCaps: `Backspace`,
    },
    en: {
      caseDown: `Backspace`,
      caseUp: `Backspace`,
      caps: `Backspace`,
      shiftCaps: `Backspace`,
    },
  },
  tab: {
    code: "Tab",
    key: "Tab",
    id: 15,
    ru: {
      caseDown: `Tab`,
      caseUp: `Tab`,
      caps: `Tab`,
      shiftCaps: `Tab`,
    },
    en: {
      caseDown: `Tab`,
      caseUp: `Tab`,
      caps: `Tab`,
      shiftCaps: `Tab`,
    },
  },
  q: {
    code: "KeyQ",
    id: 16,
    ru: {
      caseDown: `й`,
      caseUp: `Й`,
      caps: `Й`,
      shiftCaps: `й`,
    },
    en: {
      caseDown: `q`,
      caseUp: `Q`,
      caps: `Q`,
      shiftCaps: `q`,
    },
  },
  w: {
    code: "KeyW",
    id: 17,
    ru: {
      caseDown: `ц`,
      caseUp: `Ц`,
      caps: `Ц`,
      shiftCaps: `ц`,
    },
    en: {
      caseDown: `w`,
      caseUp: `W`,
      caps: `W`,
      shiftCaps: `w`,
    },
  },
  e: {
    code: "KeyE",
    id: 18,
    ru: {
      caseDown: `y`,
      caseUp: `У`,
      caps: `У`,
      shiftCaps: `у`,
    },
    en: {
      caseDown: `e`,
      caseUp: `E`,
      caps: `E`,
      shiftCaps: `e`,
    },
  },
  r: {
    code: "KeyR",
    id: 19,
    ru: {
      caseDown: `к`,
      caseUp: `К`,
      caps: `К`,
      shiftCaps: `к`,
    },
    en: {
      caseDown: `r`,
      caseUp: `R`,
      caps: `R`,
      shiftCaps: `r`,
    },
  },
  t: {
    code: "KeyT",
    id: 20,
    ru: {
      caseDown: `е`,
      caseUp: `Е`,
      caps: `Е`,
      shiftCaps: `е`,
    },
    en: {
      caseDown: `t`,
      caseUp: `T`,
      caps: `T`,
      shiftCaps: `t`,
    },
  },
  y: {
    code: "KeyY",
    id: 21,
    ru: {
      caseDown: `н`,
      caseUp: `Н`,
      caps: `Н`,
      shiftCaps: `н`,
    },
    en: {
      caseDown: `y`,
      caseUp: `Y`,
      caps: `Y`,
      shiftCaps: `y`,
    },
  },
  u: {
    code: "KeyU",
    id: 22,
    ru: {
      caseDown: `г`,
      caseUp: `Г`,
      caps: `Г`,
      shiftCaps: `г`,
    },
    en: {
      caseDown: `u`,
      caseUp: `U`,
      caps: `U`,
      shiftCaps: `u`,
    },
  },
  i: {
    code: "KeyI",
    id: 23,
    ru: {
      caseDown: `ш`,
      caseUp: `Ш`,
      caps: `Ш`,
      shiftCaps: `ш`,
    },
    en: {
      caseDown: `i`,
      caseUp: `I`,
      caps: `I`,
      shiftCaps: `i`,
    },
  },
  o: {
    code: "KeyO",
    id: 24,
    ru: {
      caseDown: `щ`,
      caseUp: `Щ`,
      caps: `Щ`,
      shiftCaps: `щ`,
    },
    en: {
      caseDown: `o`,
      caseUp: `O`,
      caps: `O`,
      shiftCaps: `o`,
    },
  },
  p: {
    code: "KeyP",
    id: 25,
    ru: {
      caseDown: `з`,
      caseUp: `З`,
      caps: `З`,
      shiftCaps: `з`,
    },
    en: {
      caseDown: `p`,
      caseUp: `P`,
      caps: `P`,
      shiftCaps: `p`,
    },
  },
  bracketleft: {
    code: "BracketLeft",
    id: 26,
    ru: {
      caseDown: `x`,
      caseUp: `X`,
      caps: `X`,
      shiftCaps: `x`,
    },
    en: {
      caseDown: `[`,
      caseUp: `{`,
      caps: `[`,
      shiftCaps: `{`,
    },
  },
  bracketright: {
    code: "BracketRight",
    id: 27,
    ru: {
      caseDown: `ъ`,
      caseUp: `Ъ`,
      caps: `Ъ`,
      shiftCaps: `ъ`,
    },
    en: {
      caseDown: `]`,
      caseUp: `}`,
      caps: `]`,
      shiftCaps: `}`,
    },
  },
  backslash: {
    code: "Backslash",
    id: 28,
    ru: {
      caseDown: `\\`,
      caseUp: `/`,
      caps: `\\`,
      shiftCaps: `/`,
    },
    en: {
      caseDown: `\\`,
      caseUp: `|`,
      caps: `\\`,
      shiftCaps: `|`,
    },
  },
  delete: {
    code: "Delete",
    key: "Delete",
    id: 29,
    ru: {
      caseDown: `Del`,
      caseUp: `Del`,
      caps: `Del`,
      shiftCaps: `Del`,
    },
    en: {
      caseDown: `Del`,
      caseUp: `Del`,
      caps: `Del`,
      shiftCaps: `Del`,
    },
  },
  capslock: {
    code: "CapsLock",
    key: "CapsLock",
    id: 30,
    ru: {
      caseDown: `CapsLock`,
      caseUp: `CapsLock`,
      caps: `CapsLock`,
      shiftCaps: `CapsLock`,
    },
    en: {
      caseDown: `CapsLock`,
      caseUp: `CapsLock`,
      caps: `CapsLock`,
      shiftCaps: `CapsLock`,
    },
  },
  a: {
    code: "KeyA",
    id: 31,
    ru: {
      caseDown: `ф`,
      caseUp: `Ф`,
      caps: `Ф`,
      shiftCaps: `ф`,
    },
    en: {
      caseDown: `a`,
      caseUp: `A`,
      caps: `A`,
      shiftCaps: `a`,
    },
  },
  s: {
    code: "KeyS",
    id: 32,
    ru: {
      caseDown: `ы`,
      caseUp: `Ы`,
      caps: `Ы`,
      shiftCaps: `ы`,
    },
    en: {
      caseDown: `s`,
      caseUp: `S`,
      caps: `S`,
      shiftCaps: `s`,
    },
  },
  d: {
    code: "KeyD",
    id: 33,
    ru: {
      caseDown: `в`,
      caseUp: `В`,
      caps: `В`,
      shiftCaps: `в`,
    },
    en: {
      caseDown: `d`,
      caseUp: `D`,
      caps: `D`,
      shiftCaps: `d`,
    },
  },
  f: {
    code: "KeyF",
    id: 34,
    ru: {
      caseDown: `а`,
      caseUp: `А`,
      caps: `А`,
      shiftCaps: `а`,
    },
    en: {
      caseDown: `f`,
      caseUp: `F`,
      caps: `F`,
      shiftCaps: `f`,
    },
  },
  g: {
    code: "KeyG",
    id: 35,
    ru: {
      caseDown: `п`,
      caseUp: `П`,
      caps: `П`,
      shiftCaps: `п`,
    },
    en: {
      caseDown: `g`,
      caseUp: `G`,
      caps: `G`,
      shiftCaps: `g`,
    },
  },
  h: {
    code: "KeyH",
    id: 36,
    ru: {
      caseDown: `р`,
      caseUp: `Р`,
      caps: `Р`,
      shiftCaps: `р`,
    },
    en: {
      caseDown: `h`,
      caseUp: `H`,
      caps: `H`,
      shiftCaps: `h`,
    },
  },
  j: {
    code: "KeyJ",
    id: 37,
    ru: {
      caseDown: `о`,
      caseUp: `О`,
      caps: `О`,
      shiftCaps: `о`,
    },
    en: {
      caseDown: `j`,
      caseUp: `J`,
      caps: `J`,
      shiftCaps: `j`,
    },
  },
  k: {
    code: "KeyK",
    id: 38,
    ru: {
      caseDown: `л`,
      caseUp: `Л`,
      caps: `Л`,
      shiftCaps: `л`,
    },
    en: {
      caseDown: `k`,
      caseUp: `K`,
      caps: `K`,
      shiftCaps: `k`,
    },
  },
  l: {
    code: "KeyL",
    id: 39,
    ru: {
      caseDown: `д`,
      caseUp: `Д`,
      caps: `Д`,
      shiftCaps: `д`,
    },
    en: {
      caseDown: `l`,
      caseUp: `L`,
      caps: `L`,
      shiftCaps: `l`,
    },
  },
  semicolon: {
    code: "Semicolon",
    id: 40,
    ru: {
      caseDown: `ж`,
      caseUp: `Ж`,
      caps: `Ж`,
      shiftCaps: `ж`,
    },
    en: {
      caseDown: `;`,
      caseUp: `:`,
      caps: `;`,
      shiftCaps: `:`,
    },
  },
  quote: {
    code: "Quote",
    id: 41,
    ru: {
      caseDown: `э`,
      caseUp: `Э`,
      caps: `Э`,
      shiftCaps: `э`,
    },
    en: {
      caseDown: `'`,
      caseUp: `"`,
      caps: `'`,
      shiftCaps: `"`,
    },
  },
  enter: {
    code: "Enter",
    key: "Enter",
    id: 42,
    ru: {
      caseDown: `Enter`,
      caseUp: `Enter`,
      caps: `Enter`,
      shiftCaps: `Enter`,
    },
    en: {
      caseDown: `Enter`,
      caseUp: `Enter`,
      caps: `Enter`,
      shiftCaps: `Enter`,
    },
  },
  shiftleft: {
    code: "ShiftLeft",
    key: "Shift",
    id: 43,
    ru: {
      caseDown: `Shift`,
      caseUp: `Shift`,
      caps: `Shift`,
      shiftCaps: `Shift`,
    },
    en: {
      caseDown: `Shift`,
      caseUp: `Shift`,
      caps: `Shift`,
      shiftCaps: `Shift`,
    },
  },
  intlbackslash: {
    code: "IntlBackslash",
    key: "\\",
    id: 44,
    ru: {
      caseDown: `\\`,
      caseUp: `\\`,
      caps: `\\`,
      shiftCaps: `\\`,
    },
    en: {
      caseDown: `\\`,
      caseUp: `\\`,
      caps: `\\`,
      shiftCaps: `\\`,
    },
  },
  z: {
    code: "KeyZ",
    id: 45,
    ru: {
      caseDown: `я`,
      caseUp: `Я`,
      caps: `Я`,
      shiftCaps: `я`,
    },
    en: {
      caseDown: `z`,
      caseUp: `Z`,
      caps: `Z`,
      shiftCaps: `z`,
    },
  },
  x: {
    code: "KeyX",
    id: 46,
    ru: {
      caseDown: `ч`,
      caseUp: `Ч`,
      caps: `Ч`,
      shiftCaps: `ч`,
    },
    en: {
      caseDown: `x`,
      caseUp: `X`,
      caps: `X`,
      shiftCaps: `x`,
    },
  },
  c: {
    code: "KeyC",
    id: 47,
    ru: {
      caseDown: `с`,
      caseUp: `С`,
      caps: `С`,
      shiftCaps: `с`,
    },
    en: {
      caseDown: `c`,
      caseUp: `C`,
      caps: `C`,
      shiftCaps: `c`,
    },
  },
  v: {
    code: "KeyV",
    id: 48,
    ru: {
      caseDown: `м`,
      caseUp: `М`,
      caps: `М`,
      shiftCaps: `м`,
    },
    en: {
      caseDown: `v`,
      caseUp: `V`,
      caps: `V`,
      shiftCaps: `v`,
    },
  },
  b: {
    code: "KeyB",
    id: 49,
    ru: {
      caseDown: `и`,
      caseUp: `И`,
      caps: `И`,
      shiftCaps: `и`,
    },
    en: {
      caseDown: `b`,
      caseUp: `B`,
      caps: `B`,
      shiftCaps: `b`,
    },
  },
  n: {
    code: "KeyN",
    id: 50,
    ru: {
      caseDown: `т`,
      caseUp: `Т`,
      caps: `Т`,
      shiftCaps: `т`,
    },
    en: {
      caseDown: `n`,
      caseUp: `N`,
      caps: `N`,
      shiftCaps: `n`,
    },
  },
  m: {
    code: "KeyM",
    id: 51,
    ru: {
      caseDown: `ь`,
      caseUp: `Ь`,
      caps: `Ь`,
      shiftCaps: `ь`,
    },
    en: {
      caseDown: `m`,
      caseUp: `M`,
      caps: `M`,
      shiftCaps: `m`,
    },
  },
  comma: {
    code: "Comma",
    id: 52,
    ru: {
      caseDown: `б`,
      caseUp: `Б`,
      caps: `Б`,
      shiftCaps: `б`,
    },
    en: {
      caseDown: `,`,
      caseUp: `<`,
      caps: `,`,
      shiftCaps: `<`,
    },
  },
  period: {
    code: "Period",
    id: 53,
    ru: {
      caseDown: `ю`,
      caseUp: `Ю`,
      caps: `Ю`,
      shiftCaps: `ю`,
    },
    en: {
      caseDown: `.`,
      caseUp: `>`,
      caps: `.`,
      shiftCaps: `>`,
    },
  },
  slash: {
    code: "Slash",
    id: 54,
    ru: {
      caseDown: `.`,
      caseUp: `,`,
      caps: `.`,
      shiftCaps: `,`,
    },
    en: {
      caseDown: `/`,
      caseUp: `?`,
      caps: `/`,
      shiftCaps: `?`,
    },
  },
  arrowup: {
    code: "ArrowUp",
    key: "ArrowUp",
    id: 55,
    ru: {
      caseDown: `↑`,
      caseUp: `↑`,
      caps: `↑`,
      shiftCaps: `↑`,
    },
    en: {
      caseDown: `↑`,
      caseUp: `↑`,
      caps: `↑`,
      shiftCaps: `↑`,
    },
  },
  shiftright: {
    code: "ShiftRight",
    key: "Shift",
    id: 56,
    ru: {
      caseDown: `Shift`,
      caseUp: `Shift`,
      caps: `Shift`,
      shiftCaps: `Shift`,
    },
    en: {
      caseDown: `Shift`,
      caseUp: `Shift`,
      caps: `Shift`,
      shiftCaps: `Shift`,
    },
  },
  controlleft: {
    code: "ControlLeft",
    key: "Control",
    id: 57,
    ru: {
      caseDown: `Ctrl`,
      caseUp: `Ctrl`,
      caps: `Ctrl`,
      shiftCaps: `Ctrl`,
    },
    en: {
      caseDown: `Ctrl`,
      caseUp: `Ctrl`,
      caps: `Ctrl`,
      shiftCaps: `Ctrl`,
    },
  },
  metaleft: {
    code: "MetaLeft",
    key: "Meta",
    id: 58,
    ru: {
      caseDown: `Win`,
      caseUp: `Win`,
      caps: `Win`,
      shiftCaps: `Win`,
    },
    en: {
      caseDown: `Win`,
      caseUp: `Win`,
      caps: `Win`,
      shiftCaps: `Win`,
    },
  },
  altleft: {
    code: "AltLeft",
    key: "Alt",
    id: 59,
    ru: {
      caseDown: `Alt`,
      caseUp: `Alt`,
      caps: `Alt`,
      shiftCaps: `Alt`,
    },
    en: {
      caseDown: `Alt`,
      caseUp: `Alt`,
      caps: `Alt`,
      shiftCaps: `Alt`,
    },
  },
  space: {
    code: "Space",
    key: " ",
    id: 60,
    ru: {
      caseDown: ` `,
      caseUp: ` `,
      caps: ` `,
      shiftCaps: ` `,
    },
    en: {
      caseDown: ` `,
      caseUp: ` `,
      caps: ` `,
      shiftCaps: ` `,
    },
  },
  altright: {
    code: "AltRight",
    key: "Alt",
    id: 61,
    ru: {
      caseDown: `Alt`,
      caseUp: `Alt`,
      caps: `Alt`,
      shiftCaps: `Alt`,
    },
    en: {
      caseDown: `Alt`,
      caseUp: `Alt`,
      caps: `Alt`,
      shiftCaps: `Alt`,
    },
  },
  controlright: {
    code: "ControlRight",
    key: "Control",
    id: 62,
    ru: {
      caseDown: `Ctrl`,
      caseUp: `Ctrl`,
      caps: `Ctrl`,
      shiftCaps: `Ctrl`,
    },
    en: {
      caseDown: `Ctrl`,
      caseUp: `Ctrl`,
      caps: `Ctrl`,
      shiftCaps: `Ctrl`,
    },
  },
  arrowleft: {
    code: "ArrowLeft",
    key: "ArrowLeft",
    id: 63,
    ru: {
      caseDown: `←`,
      caseUp: `←`,
      caps: `←`,
      shiftCaps: `←`,
    },
    en: {
      caseDown: `←`,
      caseUp: `←`,
      caps: `←`,
      shiftCaps: `←`,
    },
  },
  arrowdown: {
    code: "ArrowDown",
    key: "ArrowDown",
    id: 64,
    ru: {
      caseDown: `↓`,
      caseUp: `↓`,
      caps: `↓`,
      shiftCaps: `↓`,
    },
    en: {
      caseDown: `↓`,
      caseUp: `↓`,
      caps: `↓`,
      shiftCaps: `↓`,
    },
  },
  arrowright: {
    code: "ArrowRight",
    key: "ArrowRight",
    id: 65,
    ru: {
      caseDown: `→`,
      caseUp: `→`,
      caps: `→`,
      shiftCaps: `→`,
    },
    en: {
      caseDown: `→`,
      caseUp: `→`,
      caps: `→`,
      shiftCaps: `→`,
    },
  },
};
